"use strict";
exports.__esModule = true;
exports.contracts = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.contracts = require("./contracts");
