/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { StarvingChildren__factory } from "./StarvingChildren__factory";
export { ThoughtsAndPrayers__factory } from "./ThoughtsAndPrayers__factory";
export { Vendor__factory } from "./Vendor__factory";
