"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
exports.__esModule = true;
exports.Vendor__factory = exports.ThoughtsAndPrayers__factory = exports.StarvingChildren__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var StarvingChildren__factory_1 = require("./StarvingChildren__factory");
__createBinding(exports, StarvingChildren__factory_1, "StarvingChildren__factory");
var ThoughtsAndPrayers__factory_1 = require("./ThoughtsAndPrayers__factory");
__createBinding(exports, ThoughtsAndPrayers__factory_1, "ThoughtsAndPrayers__factory");
var Vendor__factory_1 = require("./Vendor__factory");
__createBinding(exports, Vendor__factory_1, "Vendor__factory");
