"use strict";
exports.__esModule = true;
exports.erc721 = exports.erc20 = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.erc20 = require("./ERC20");
exports.erc721 = require("./ERC721");
