"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
exports.__esModule = true;
exports.IERC20__factory = exports.ERC20__factory = exports.extensions = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.extensions = require("./extensions");
var ERC20__factory_1 = require("./ERC20__factory");
__createBinding(exports, ERC20__factory_1, "ERC20__factory");
var IERC20__factory_1 = require("./IERC20__factory");
__createBinding(exports, IERC20__factory_1, "IERC20__factory");
