"use strict";
exports.__esModule = true;
exports.introspection = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.introspection = require("./introspection");
